#!/usr/bin/env python3

import os
import sys
import time

sys.path.append(os.path.join(
	os.path.dirname(__file__),
	"ediplug-py", "src", "ediplug"))

import smartplug

def log(*args, **kwargs):
	print(*args, **kwargs)
	sys.stdout.flush()

plug_ip="192.168.1.80"
plug_user="admin"
plug_password="1234"
plug_refresh_rate=5

def main():
	while True:
		plug = smartplug.SmartPlug(plug_ip, (plug_user, plug_password))
		log(plug.state, plug.power+"w")
		time.sleep(plug_refresh_rate)

if __name__ == "__main__":
	main()
