#!/usr/bin/env python3

import os
import sys
import time

sys.path.append(os.path.join(
	os.path.dirname(__file__),
	"ediplug-py", "src", "ediplug"))

import smartplug

def log(*args, **kwargs):
	print(*args, **kwargs)
	sys.stdout.flush()

def main():
	while True:
		time.sleep(1)
		log("Still here")

if __name__ == "__main__":
	main()
