#!/usr/bin/env python3

import json
import os
import socket
import sys
import time
import tornado
import tornado.ioloop

import thriftpy
import thriftpy.tornado
thriftpy.install_import_hook()
import ediplug_thrift

sys.path.append(os.path.join(
	os.path.dirname(__file__),
	"ediplug-py", "src", "ediplug"))

import smartplug

def log(*args, **kwargs):
	print("backend:", *args, **kwargs)
	sys.stdout.flush()

configuration = {
	"plugs": {
		"hue": {
			"ip": "192.168.1.80",
			"username": "admin",
			"password": "1234"
		}
	},
	"refresh_rate": 5
}


class StatisticsWriter(object):
	def __init__(self):
		self.output_file = open("data.csv", 'a', 1)
		self.latest_measurements = [0.0]

	def add_measurements(self, measurements):
		self.latest_measurements = measurements
		datas = str.join(" ",
			[str(measurement) for measurement in measurements])
		self.output_file.write(str(time.time())+" "+datas+"\n")

	def get_latest_measurements(self):
		return self.latest_measurements


class Backend(object):
	def __init__(self):
		self.writer = StatisticsWriter()
		log("Starting backend")
		self.ioloop = tornado.ioloop.IOLoop.current()
		self.measurementTask = tornado.ioloop.PeriodicCallback(
			self.getMeasurements, configuration["refresh_rate"]*1000)
		self.server = thriftpy.tornado.make_server(
			ediplug_thrift.Ediplug, self, io_loop=self.ioloop)
		self.selfCheckTask = tornado.ioloop.PeriodicCallback(
			self.checkServer, 1000)

	def getMeasurements(self):
		plugs = [
			smartplug.SmartPlug(plug["ip"], (plug["username"], plug["password"]))
			for plug in configuration["plugs"].values()]
		self.writer.add_measurements([float(plug.power) for plug in plugs])

	@tornado.gen.coroutine
	def checkServer(self):
		client = yield thriftpy.tornado.make_client(
			ediplug_thrift.Ediplug, '127.0.0.1', 6000)
		result = yield client.getCurrentConsumption()
		client.close()
		assert(result == self.getCurrentConsumption())

	def getCurrentConsumption(self):
		currentConsumption = self.writer.get_latest_measurements()[0]
		return currentConsumption

	def run(self):
		self.measurementTask.start()
		self.selfCheckTask.start()
		self.server.listen(6000)
		self.ioloop.start()


def main():
	backend = Backend()
	backend.run()

if __name__ == "__main__":
	main()
