#!/usr/bin/env python3

import tornado
import tornado.web
import tornado.httpserver
import tornado.ioloop
import tornado.gen
import sys

import thriftpy
import thriftpy.tornado
thriftpy.install_import_hook()
import ediplug_thrift


def log(*args, **kwargs):
	print("frontend:", *args, **kwargs)
	sys.stdout.flush()

class EdiplugServer(tornado.web.RequestHandler):

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.ioloop = tornado.ioloop.IOLoop.current()

	@tornado.gen.coroutine
	def get(self):
		client = yield thriftpy.tornado.make_client(
			ediplug_thrift.Ediplug, '127.0.0.1', 6000)
		currentConsumption = yield client.getCurrentConsumption()
		self.write(str(currentConsumption)+"W")


def main():
	log("Starting web server")
	application = tornado.web.Application(
			[(r"/", EdiplugServer)])
	application.listen(8888)
	tornado.ioloop.IOLoop.current().start()

if __name__ == "__main__":
	main()
