#!/usr/bin/env python3

import tornado
import tornado.web
import tornado.httpserver
import tornado.ioloop
import tornado.gen
import sys

def log(*args, **kwargs):
	print(*args, **kwargs)
	sys.stdout.flush()

class ediplugServer(tornado.web.RequestHandler):

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.ioloop = tornado.ioloop.IOLoop.current()

	@tornado.gen.coroutine
	def get(self):
		self.write("Hello before delay\n")
		yield tornado.gen.Task(self.ioloop.call_later, 1)
		self.write("Hello delayed world\n")

def main():
	log("Starting web server")
	application = tornado.web.Application(
			[(r"/", ediplugServer)])
	application.listen(8888)
	tornado.ioloop.IOLoop.current().start()

if __name__ == "__main__":
	main()
